# Prometheus configuration for CrewAI Pandoc Agent monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'pandoc-agent'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s
    
  - job_name: 'pandoc-agent-api'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 15s
    metrics_path: /status
    scrape_timeout: 5s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Example alerting rules (uncomment and customize as needed)
# rule_files:
#   - pandoc_alerts.yml